"""Добавили таблицу для новостей о разработках

Revision ID: 9c987e3f9798
Revises: 1a6df0bfaaed
Create Date: 2023-06-10 15:57:47.517094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c987e3f9798'
down_revision = '1a6df0bfaaed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developer_news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('developer_news')
    # ### end Alembic commands ###
